const USERDELETE_REQUEST = 'USERDELETE_REQUEST';
const USERDELETE_SUCCESS = 'USERDELETE_SUCCESS';
const USERDELETE_FAILURE = 'USERDELETE_FAILURE';

// export actions types
const UserDeleteActionTypes = {
  USERDELETE_REQUEST,
  USERDELETE_SUCCESS,
  USERDELETE_FAILURE,
};

export default UserDeleteActionTypes;
